# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Area')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Price')),
                ('latitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitude')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Area',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone Number')),
                ('language', models.CharField(blank=True, max_length=150, null=True, verbose_name='Language')),
                ('Currency', models.CharField(blank=True, max_length=150, null=True, verbose_name='Currency')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provider Entry',
                'verbose_name_plural': 'Provider Entries',
            },
        ),
        migrations.AddField(
            model_name='polygon',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
